name: CI

on:
  pull_request:
    branches:
      - dev
      - staging
      - prod
  push:
    branches:
      - main  

jobs:

  frontend-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm test


  backend-tests:
    runs-on: ubuntu-latest
    env:
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
    
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        run: npm ci

      - name: Run backend tests
        run: npm test