name: Production Pipeline

on:
  push:
    branches: [prod]

permissions:
  id-token: write
  contents: read

jobs:

  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: "prod"

  build:
    needs: terraform
    uses: ./.github/workflows/build.yml
    with:
      backend_repo: ${{ needs.terraform.outputs.backend_repo }}
      frontend_repo: ${{ needs.terraform.outputs.frontend_repo }}
      role: ${{ needs.terraform.outputs.role }}

  deploy:
    needs: [terraform, build]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "prod"
      cluster_name: ${{ needs.terraform.outputs.cluster_name }}
      image_tag: ${{ needs.build.outputs.image_tag }}
      backend_repo: ${{ needs.terraform.outputs.backend_repo }}
      frontend_repo: ${{ needs.terraform.outputs.frontend_repo }}
      role: ${{ needs.terraform.outputs.role }}