name: Destroy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string  

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra/envs/${{ inputs.environment }} 
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_BOOTSTRAP_ROLE }}
          aws-region: us-east-1   
      
      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform init
        run: terraform init
      
      - name: Terraform Plan
        env:
          TF_VAR_project: ${{ secrets.TF_VAR_PROJECT }}
          TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
          TF_VAR_github_org: ${{ secrets.TF_VAR_GITHUB_ORG }}
          TF_VAR_github_repo: ${{ secrets.TF_VAR_GITHUB_REPO }}
          TF_VAR_subnet_ids: ${{ secrets.TF_VAR_SUBNET_IDS }}
          
          TF_VAR_public_subnet_tags_1: '{ "Name": "public-subnet-1-${{ inputs.environment }}" }'
          TF_VAR_public_subnet_tags_2: '{ "Name": "public-subnet-2-${{ inputs.environment }}" }'
          TF_VAR_igw_tags: '{ "Name": "igw-${{ inputs.environment }}" }'
          TF_VAR_rt_tags: '{ "Name": "rt-${{ inputs.environment }}" }'
          TF_VAR_sg_tags: '{ "Name": "sg-${{ inputs.environment }}" }' 
        run: terraform plan -var "environment=${{ inputs.environment }}" -input=false
        
        
      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
            -var "environment=${{ inputs.environment }}"