name: Terraform

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      backend_repo:
        value: ${{ jobs.aws_infra.outputs.backend_repo }}/myapp-dev-node
      frontend_repo:
        value: ${{ jobs.aws_infra.outputs.frontend_repo }}/myapp-dev-react
      cluster_name: 
        value: ${{ jobs.aws_infra.outputs.cluster_name }}  
      role: 
        value: ${{ jobs.aws_infra.outputs.role }}     

permissions:
  id-token: write
  contents: read

jobs:
  #  AWS INFRASTRUCTURE
  aws_infra:
    runs-on: ubuntu-latest
    env:
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_project: ${{ secrets.TF_VAR_PROJECT }}
      TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
      TF_VAR_github_org: ${{ secrets.TF_VAR_GITHUB_ORG }}
      TF_VAR_github_repo: ${{ secrets.TF_VAR_GITHUB_REPO }}
      TF_VAR_subnet_ids: ${{ secrets.TF_VAR_SUBNET_IDS }}
      TF_VAR_public_subnet_tags_1: '{ "Name": "public-subnet-1-${{ inputs.environment }}" }'
      TF_VAR_public_subnet_tags_2: '{ "Name": "public-subnet-2-${{ inputs.environment }}" }'
      TF_VAR_igw_tags: '{ "Name": "igw-${{ inputs.environment }}" }'
      TF_VAR_rt_tags: '{ "Name": "rt-${{ inputs.environment }}" }'
      TF_VAR_sg_tags: '{ "Name": "sg-${{ inputs.environment }}" }'

    defaults:
      run:
        working-directory: ./infra/envs/${{ inputs.environment }}/aws

    outputs:
      cluster_name: ${{ steps.outputs.outputs.cluster_name }}
      backend_repo: ${{ steps.outputs.outputs.backend_repo }}
      frontend_repo: ${{ steps.outputs.outputs.frontend_repo }}
      role: ${{ steps.role_ID.outputs.deploy_role_arn }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_BOOTSTRAP_ROLE }}
          aws-region: us-east-1

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Export Outputs
        id: outputs
        run: |
          echo "cluster_name=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
          echo "backend_repo=$(terraform output -raw backend_repo_url)" >> $GITHUB_OUTPUT
          echo "frontend_repo=$(terraform output -raw frontend_repo_url)" >> $GITHUB_OUTPUT

      - name: Export role output based on branch
        id: role_ID
        run: |
          echo "deploy_role_arn=$(terraform output -raw deploy_role_arn -no-color)" >> $GITHUB_OUTPUT


  #  KUBERNETES (NAMESPACES, RBAC)
  k8s:
    runs-on: ubuntu-latest
    needs: aws_infra 

    defaults:
      run:
        working-directory: ./infra/envs/${{ inputs.environment }}/k8s

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_BOOTSTRAP_ROLE }}
          aws-region: us-east-1

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var "environment=${{ inputs.environment }}" -input=false

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var "environment=${{ inputs.environment }}" -input=false
   